//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPOINTMENT
    {
        public int appointmentID { get; set; }
        public Nullable<int> doctorID { get; set; }
        public Nullable<int> patientID { get; set; }
        public string department { get; set; }
        public string doctorName { get; set; }
        public string doctorSurname { get; set; }
        public string patientName { get; set; }
        public string patientSurname { get; set; }
        public Nullable<System.DateTime> appointmentDate { get; set; }
        public Nullable<System.TimeSpan> appointmentHour { get; set; }
    
        public virtual DOCTOR DOCTOR { get; set; }
        public virtual PATIENT PATIENT { get; set; }
    }
}
